### ISSUE TITLE
How to use TypeName to generate nullable primitives? 

### ISSUE THREAD

**Issue by Zhuinden** [square/kotlinpoet#69] opened 2017-05-18 18:19 UTC
The docs mention it as a possibility but how exactly is it done?

**Comment by Zhuinden** [comment] 2017-05-18 18:37
Oh it is worked on in https://github.com/square/kotlinpoet/pull/70

**Comment by JakeWharton** [comment] 2017-05-18 19:49
Dupe of #35

**Closed by JakeWharton** 2017-05-18 19:49 UTC

**Comment by Zhuinden** [comment] 2017-08-10 22:33
So, `typeName.asNullable()`
