### ISSUE TITLE
Functions with receivers instead of chained builders

### ISSUE THREAD

**Issue by ilya-g** [square/kotlinpoet#65] opened 2017-05-16 21:47 UTC
In Kotlin DSLs it's a common pattern to provide a factory function taking a function with receiver, which setups the instance being built, so that instead of:
```
FunSpec.builder("main")
        .addParameter(ArrayTypeName.of(String::class), "args")
        .addStatement("%T(args[0]).greet()", greeterClass)
        .build()
```

one can write
```
FunSpec("main") {
    parameter(ArrayTypeName.of(String::class), "args")
    statement("%T(args[0]).greet()", greeterClass))
}
```

FunSpec has the signature like the following:
```
fun FunSpec(name: String, init: FunSpec.Builder.() -> Unit): FunSpec = 
    FunSpec.builder(name).apply(init).build()
```

**Comment by JakeWharton** [comment] 2017-05-16 22:08
Yeah we haven't touched the API yet with regard to changing it from JavaPoet. Mostly focused on getting the output correct before trying to make the API more idiomatic.

**Comment by burntcookie90** [comment] 2017-05-16 23:09
couldn't this just be accomplished with `apply`?

```kotlin
FunSpec.builder("main").apply {
  addParameter(...)
  addStatement(...)
  build()
}
```

**Comment by ilya-g** [comment] 2017-05-17 03:45
@burntcookie90 Nope. You still have to type `builder`, `build`, `apply` and prefix parameter and statement declarations with `add`.

**Comment by JakeWharton** [comment] 2017-09-05 21:45
There's three issues about the API. Closing this as a dupe of #62.

**Closed by JakeWharton** 2017-09-05 21:45 UTC
