### ISSUE TITLE
Aliased imports not used when generating code in same package for which the aliased import is defined

### ISSUE THREAD

**Issue by mcarleio** [square/kotlinpoet#1839] opened 2024-02-23 23:42 UTC
**Describe the bug**
An aliased import added via `addAliasedImport` for a class in the **same** package is not used.

**To Reproduce**
```kotlin
package org.example

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec

class PersonId

fun main() {
    println(
        FileSpec.builder("org.example", "SomeFile")
            .addAliasedImport(PersonId::class, "PID")
            .addFunction(
                FunSpec.builder("pid")
                    .returns(PersonId::class)
                    .addCode("return %T()", PersonId::class)
                    .build()
            )
            .build()
    )
}
```

**Expected behavior**
```kotlin
package org.example

import org.example.PersonId as PID

public fun pid(): PID = PID()
```

**Actual behavior**
```kotlin
package org.example

import org.example.PersonId as PID

public fun pid(): PersonId = PersonId()
```

**Additional context**

If you change the package of the FileSpec to a different package than the PersonId class (e.g. `FileSpec.builder("org.elsewhere", "SomeFile")`), it correctly uses the aliases import:

```kotlin
package org.elsewhere

import org.example.PersonId as PID

public fun pid(): PID = PID()
```

**Comment by Egorand** [comment] 2024-02-24 17:58
I'm not able to reproduce this with a unit test on the latest master. It looks like a duplicate of #1696, which was fixed in [1.16.0](https://github.com/square/kotlinpoet/releases/tag/1.16.0) - please make sure you're using the latest version of the library.

**Closed by Egorand** 2024-02-24 17:58 UTC
Labels: bug
