### ISSUE TITLE
Kind.OBJECT can't add property?

### ISSUE THREAD

**Issue by VictorChow** [square/kotlinpoet#134] opened 2017-06-19 11:19 UTC
Hi, why do check() when adding a single property while addProperties() not?

0.3.0    TypeSpec.kt   line:403 
fun addProperties(propertySpecs: Iterable<PropertySpec>) = apply {
      this.propertySpecs += propertySpecs
 }

fun addProperty(propertySpec: PropertySpec) = apply {
      **check(kind == Kind.CLASS || kind == Kind.ENUM || kind == Kind.ANNOTATION) {
        "cannot add property $propertySpec to $kind"
      }**
      propertySpecs += propertySpec
}

**Comment by VictorChow** [comment] 2017-06-19 11:23
TypeSpec.objectBuilder can't add single property

**Comment by JakeWharton** [comment] 2017-06-19 12:45
Dupe of #119. Already fixed on master.

**Closed by JakeWharton** 2017-06-19 12:45 UTC
