### ISSUE TITLE
Type MutableList gets converted to List

### ISSUE THREAD

**Issue by mc-lovin** [square/kotlinpoet#482] opened 2018-09-23 23:33 UTC
When I trying to use MutableList class, it sometimes gets converted to just List

example
```
    val funSpec = FunSpec.constructorBuilder()
        .addParameter("list", MutableList::class.parameterizedBy(Int::class))
        .build()
```

gets converted to

```
constructor(list: kotlin.collections.List<kotlin.Int>)
```

while it should be 
```
constructor(list: MutableList<kotlin.Int>)
```

**Comment by JakeWharton** [comment] 2018-09-23 23:40
There's no such type as `MutableList` at runtime so  the library only sees the runtime type. If you need `MutableList` then you'll need to use a `ClassName` to create it.

**Comment by Egorand** [comment] 2018-09-26 00:05
Dupe of #279

**Closed by Egorand** 2018-09-26 00:05 UTC
