### ISSUE TITLE
Is there a way to make KotlinPoet more idiomatic?

### ISSUE THREAD

**Issue by breandan** [square/kotlinpoet#435] opened 2018-08-05 16:09 UTC
Just started [using](https://github.com/breandan/yuri/blob/6605720c9ecb9f9cc9cb04fa2c10a9c2867e46f2/build.gradle.kts#L126) KotlinPoet and it's nice, if a [bit tricky](https://github.com/square/kotlinpoet/issues/434) to figure out what's going on sometimes. Thanks for the help!

I wonder if it's possible to make the Kotlin API more idiomatic. It seems like you're using the same style as the [Java version](https://github.com/square/javapoet), just adapted to Kotlin syntax features. Have you thought about using a more fluent DSL (e.g. via [type-safe builders](https://kotlinlang.org/docs/reference/type-safe-builders.html))?

I found [this project](https://github.com/jonnyzzz/kotlin.generator) which attempts to, "make Kotlin code generating code to looks as close as possible to a code it generates," but I wasn't able to find any examples. @jonnyzzz

**Comment by Egorand** [comment] 2018-08-05 16:31
There has been a discussion about switching to DSL style and we decided to postpone the decision. From a personal perspective, builders seem to work well in Kotlin so I don't see any reason for changing to a different API style. Are there any specific APIs that you think will work better with DSL?

**Comment by JakeWharton** [comment] 2018-08-05 17:10
DSLs assume you're building the entire object at once and in practice the opposite is usually true for code generation. You pass around builders for multiple functions to contribute to and then assemble at the end.

**Comment by JakeWharton** [comment] 2018-08-05 17:11
Also dupe of #62. Place any thoughts there.

**Closed by JakeWharton** 2018-08-05 17:11 UTC
