### ISSUE TITLE
Allow the users to define properties without explicitly stating the type

### ISSUE THREAD

**Issue by notsodistantworlds** [square/kotlinpoet#1014] opened 2020-11-14 20:04 UTC
I've been trying to generate a JUnit test which uses Testcontainers, but i cannot define a property with the type `PostgreSQLContainer` because of how Testcontainers did their polymorphism. They're using that trick of `PostgreSQLContainer<SELF: PostgreSQLContainer<SELF>>` which basically allows subclasses to return themselves, allowing for method chaining. 

This does not interoperate with Kotlin (at all), it's impossible to ever mention this type in Kotlin. Which is fine though, because you'd never explicitly mention this type, instead you assign `PostgreSQLContainerProvider().newInstance().build()` to an implicitly typed field.

Unfortunately, that doesn't seem to be possible with kotlinpoet at the moment. To create a `PropertySpec`, you *must* specify a type. Which doesn't really seem to add anything good to the system anyway.

Could `PropertySpec.Builder` be changed so that it does not absolutely require a type?

I guess what i can try for now is read the generated file and manually remove the `: PostgreSQLContainer` afterwards, but that's quite ugly.

**Comment by ZacSweers** [comment] 2020-11-14 20:34
Can you give a full sample snippet of what you're trying to generate and the API you'd need? Not sure I grok what you're asking

**Comment by notsodistantworlds** [comment] 2020-11-14 21:05
So in my original (hand-written) test i had the following
```kt
class Entity_DBAccess_Test {
  companion object {
    val container = PostgreSQLContainerProvider().newInstance()
      .withDatabaseName("dbname")
      .withUsername("test")
      .withPassword("test")
      .withInitScript("schema.sql")
      //...
  }
  //...
}
```
and i'm now trying to fit this into kotlinpoet to generate the same test for all the entities. I have the following code
```kt
TypeSpec.classBuilder(test_name)
    .addType(TypeSpec.companionObjectBuilder()
        .addProperty(PropertySpec.builder("container", PostgreSQLContainer::class.asClassName().parameterizedBy(WildcardTypeName.producerOf(ANY)))
            .initializer("""
                    PostgreSQLContainerProvider().newInstance()
                    .withDatabaseName("dbname")
                    .withUsername("test")
                    .withPassword("test")
                    .withInitScript("schema.sql")
                """.trimIndent())
            .build()
        ).build()
    ).build()
```
which outputs the following
```kt
public class Entity_DBAccess_Test {
  public companion object {
    public val container: PostgreSQLContainer<out Any> = PostgreSQLContainerProvider().newInstance()
        .withDatabaseName("dbname")
        .withUsername("test")
        .withPassword("test")
        .withInitScript("schema.sql")
      //...
  }
  //...
}
```
I've tried to find some combination of generic parameters that would work here, and eventually started googling around. Turns out this is a common issue, Kotlin just doesn't support this `SELF` trickery, but usually it can be worked around. In this case, not stating the type explicitly would work.

**Comment by ZacSweers** [comment] 2020-11-14 23:31
What is the type of the property if it's not explicitly set (I.e. in your hand written code). If it's different, why can't you just set it to that in your code generation?

I could see a possible space for something like `PropertySpec.expressionBuilder(String, CodeBlock)` but want to understand your use case here better first as it's not clear to me why your generated snippet is wrong.

**Comment by notsodistantworlds** [comment] 2020-11-14 23:47
IntelliJ reports the field type as `JdbcDatabaseContainer<*>!><*>!>!`. Which... i don't even think that's valid Kotlin code:
![image](https://user-images.githubusercontent.com/23058451/99159334-1b754000-26e4-11eb-9c8a-a2bc114d9d11.png)

Unsurprisingly, that doesn't compile:
![image](https://user-images.githubusercontent.com/23058451/99159379-6a22da00-26e4-11eb-91df-df42c6e9239e.png)

So i guess in a way this is also a bug in Kotlin, it definitely should be handling this better.

**Comment by JakeWharton** [comment] 2020-11-15 01:52
Dupe of #858.

**Closed by JakeWharton** 2020-11-15 01:52 UTC

**Comment by YudingZhou** [comment] 2022-09-22 02:36
any solution so far
