### ISSUE TITLE
Annotation as a constructor parameter for AnnotationSpec

### ISSUE THREAD

**Issue by AlecStrong** [square/kotlinpoet#292] opened 2017-12-01 19:25 UTC
Not sure if theres a way to do it currently with `addMember` but I dont think theres currently a way to generate the code in the example for this:

https://kotlinlang.org/docs/reference/annotations.html#constructors

```
@Deprecated("This function is deprecated, use === instead", ReplaceWith("this === other"))
```

**Comment by JakeWharton** [comment] 2017-12-01 19:31
Dupe of #215 see #240.

**Closed by JakeWharton** 2017-12-01 19:31 UTC

**Comment by AlecStrong** [comment] 2017-12-01 19:40
right but i want to reuse the `AnnotationSpec` API for the annotation parameter.

**Comment by AlecStrong** [comment] 2017-12-01 19:42
If I just `toString` an `AnnotationSpec` it has the `@` in front, so theres currently no way (that I know of) to use an `AnnotationSpec` in a `CodeBlock` which is what the current `addMember` api requires

**Comment by JakeWharton** [comment] 2017-12-01 19:43
The tests use `%L` for it.

https://github.com/Egorand/kotlinpoet/blob/455c3a67a8cba64ed7ad1f3296384e1ff593f187/src/test/java/com/squareup/kotlinpoet/TypeSpecTest.kt#L1037-L1065

**Comment by AlecStrong** [comment] 2017-12-01 19:53
Danke ill try that

**Comment by Egorand** [comment] 2017-12-01 20:51
Oh btw, should annotation args use continuation indent? @JakeWharton

**Comment by JakeWharton** [comment] 2017-12-01 20:54
I think so, yes, because they're basically function/ctor invocations.

**Comment by Egorand** [comment] 2017-12-01 21:25
So **param** lists use single indent, and **arg** lists use double indent.

**Comment by JakeWharton** [comment] 2017-12-01 21:27
Yep
