### ISSUE TITLE
Omit modifier for override parameters in constructor and it's override function

### ISSUE THREAD

**Issue by Omico** [square/kotlinpoet#1548] opened 2023-05-16 07:57 UTC
![image](https://github.com/square/kotlinpoet/assets/14316223/e4e9c7a5-559e-4e0a-9d46-bf6c3e15e81e)

Explicit API mode is set as strict.

Also, override function as well.

**Comment by JakeWharton** [comment] 2023-05-16 10:31
Dupe of #1301

**Comment by JakeWharton** [comment] 2023-05-16 19:22
Sorry I read the screenshot and not the title. Thought it was about `public` members on an `internal` type.

**Comment by Omico** [comment] 2023-05-16 20:08
No worries! Please review it carefully. Hope I didn't mess up the tests.

**Closed** 2023-05-19 12:19 UTC
Labels: bug
