### ISSUE TITLE
[Request] Add writeTo(Filer)

### ISSUE THREAD

**Issue by AllanWang** [square/kotlinpoet#467] opened 2018-09-09 23:02 UTC
I'm currently experimenting with code generation, and I saw that `writeTo(Filer)` [existed in JavaPoet](https://github.com/square/javapoet/blob/d91f8e1374f7ccdb68d92c206c84864cd09c02f6/src/main/java/com/squareup/javapoet/JavaFile.java#L108) but not here. I have replicated the method in kotlin:

```
/** Writes this to [filer]. */
@Throws(IOException::class)
fun writeTo(filer: Filer) {
    val fileName = if (packageName.isEmpty()) name
    else "$packageName.$name"
    val fileObject = filer.createSourceFile(fileName)
    // Attempt to write, close the writer, and delete if failed
    try {
        fileObject.openWriter().use {
            writeTo(it)
        }
    } catch (e: Exception) {
        fileObject.delete()
        throw e
    }
}
```

Currently, there is a lack of `originatingElements` passed to the filer, and there is no test for the method.

If writing from `AbstractProcessor` was meant to be done some other way, please let me know.

**Comment by Egorand** [comment] 2018-09-12 14:04
Closing as a duplicate of #105, let me know if this is a request for different functionality, otherwise feel free to comment on that ticket.

**Closed by Egorand** 2018-09-12 14:04 UTC
