### ISSUE TITLE
Expression bodies with returns can be generated

### ISSUE THREAD

**Issue by ansman** [square/kotlinpoet#603] opened 2019-01-14 21:40 UTC
You are not allowed to have returns when using expression bodies. Here is a test that illustrates the problem:
```kotlin
val source = FileSpec.builder(tacosPackage, "Taco")
    .addFunction(FunSpec.builder("addA")
        .addParameter("s", String::class)
        .returns(String::class.asClassName().copy(nullable = true))
        .addStatement("return s ?: return null + %S", "a")
        .build())
    .build()
assertThat(source.toString()).isEqualTo("""
    |package com.squareup.tacos
    |
    |import kotlin.String
    |
    |fun addA(s: String): String {
    |    return s ?: return null + "a"
    |}
    |""".trimMargin())
```
The test fails because the generated code looks like this:
```kotlin
package com.squareup.tacos
    
import kotlin.String
    
fun addA(s: String): String? = s ?: return null + "a"
```

**Comment by Egorand** [comment] 2019-01-14 21:55
Isn't this equivalent to `return s ?: null + "a"`?

**Comment by ansman** [comment] 2019-01-14 21:57
No, it's equivalent to:
```kotlin
if (s == null) return null else s + "a"
```

Please note that this was just an example to illustrate the problem.

**Comment by Egorand** [comment] 2019-01-14 22:23
Yeah, it's confusing, I would've written it as `return if (s == null) null else s + "a"` or `return s?.let { it + "a" }`. Wanna take crack at it? 
Would you expect that code to not emit a single-expression function if there's a second "return" hidden somewhere in the function body? I think it might become complicated if we consider string literals containing the word `"return"`.

**Comment by Egorand** [comment] 2019-01-14 22:31
What if that `codeBlock` contains new lines and cannot be emitted as an expression body? That can easily happen if you start passing a different `codeBlock` and forget to change `expressionBody` into something different.
I like that we don't force extra APIs on people and pick the best way to emit the body based on the content.

**Comment by ansman** [comment] 2019-01-14 22:34
Expression bodies can contain newlines, as long as it's a part of the same statement.

It's nice to have it automatic but also a bit annoying since you cannot opt out (perhaps you prefer to not use an expression body in some cases).

With an explicit API you at least make sure that you have to make your code be compatible with expression bodies.

**Comment by JakeWharton** [comment] 2019-01-14 22:37
I think I would rather just disable the feature than provide an explicit API. The economics of generated code are such that we don't really need the syntactic optimization.

**Comment by Egorand** [comment] 2019-01-14 22:49
It's definitely an option, however I think this function has mostly worked well for us and I'd hate to remove it. This specific bug is caused by non-straightforward code that's easy to refactor so that it doesn't break KotlinPoet.

**Comment by swankjesse** [comment] 2019-01-15 04:11
Yeah, this seems unlikely to be a problem in practice.

**Comment by Egorand** [comment] 2019-03-02 22:10
Closing this, there doesn't seem to be a legit test case that can't be rewritten in a more straightforward fashion thus eliminating the issue.

**Closed by Egorand** 2019-03-02 22:10 UTC
Labels: bug
