### ISSUE TITLE
FunSpec.overring(ExecutableElement) does not correctly declare nullable primitives and Strings

### ISSUE THREAD

**Issue by TheWishWithin** [square/kotlinpoet#585] opened 2019-01-03 23:27 UTC
If you override a Kotlin interface which has nullable `Int`, `Float` etc. or `kotlin.String`, the overridden method will be declared using `java.lang.Integer`, `java.lang.String` etc. instead of `Int?` or `String`.

This happens when you use a `javax.lang.model.element.ExecutableElement` with an annotation processor for example.

**Example 1:**
Override the following: 
``fun test(value: String)``

The generate Kotlin file will contain `import java.lang.String` and therefore the overridden method signature no longer matches the interface method.

**Example 2:**
Override the following:
``fun bla(blub: Int?)``

The generated Kotlin file will contain ``import java.lang.Integer`` and will be generate like this:
``override fun bla(blub: Integer)``
It also is not nullable. It should be generate like this:
``override fun bla(blub: Int?)

**Comment by Egorand** [comment] 2019-01-04 14:08
See #236 for more context.

The root of the problem is that `kotlin.String`, `kotlin.Int` and other are compile-time only types: the Kotlin compiler will replace them with `java.lang.String` and `java.lang.Integer` or `int` respectively when producing the bytecode, and these are the types that you see during the annotation processing step. Similarly, many other Kotlin features, such as nullable types, delegates, etc., don't have a direct representation in bytecode. Good news is that this information is not lost - it's preserved in binary format in a `@Metadata` annotation inside the class file. Bad news is that accessing this information is not trivial. Since there's just a single `@Metadata` annotation per class file, you can't access it via `ExecutableElement`, you'd have to find the enclosing element that represents the type declaration - that element will have the annotation attached to it. Currently this is out of scope for KotlinPoet, cause usually the library doesn't have enough context to access `@Metadata`, but we were discussing building a helper library that would assist in using KotlinPoet with annotation processors - no ETA at the moment. If you're interested in digging further - there are currently (AFAIK) two frameworks that allow you to access and parse `@Metadata` to extract information about Kotlin-specific features - [Takhion/kotlin-metadata](https://github.com/Takhion/kotlin-metadata) and JetBrains' [kotlinx-metadata](https://github.com/JetBrains/kotlin/tree/master/libraries/kotlinx-metadata), plus check how [Moshi](https://github.com/square/moshi/tree/master/kotlin/codegen) solves a similar problem.

**Closed** 2019-01-06 16:12 UTC
