### ISSUE TITLE
TypeMirror.asTypeName() returns java.lang.String when receiver type is kotlin.String

### ISSUE THREAD

**Issue by hotchemi** [square/kotlinpoet#236] opened 2017-09-17 13:12 UTC
## Overview

Thx for amazing library!

I encountered a problem that `TypeMirror.asTypeName()` returns `java.lang.String` when receiver type is `kotlin.String`. It seems this is a bug so currently we inserted a workaround below to avoid that.

```kotlin
fun TypeName.correctStringType() =
    if (this.toString() == "java.lang.String") ClassName("kotlin", "String") else this
```

**Comment by JakeWharton** [comment] 2017-09-19 01:42
It's not *really* a bug. Kotlin uses a Java string when run on the JVM so that's what you see when using introspection APIs. Your workaround will incorrectly change non-Kotlin string types into Kotlin ones and it doesn't cover the hundreds of other JVM types that Kotlin ones map directly to.

**Comment by hotchemi** [comment] 2017-09-19 02:44
Thx!

I understood the rationale and let me elaborate the situation I encountered.
Think about generating some pieces of code with annotation processor(kapt) like below.

```kotlin
@MarkerAnnotation
fun hoge(arg: String) {
  // do something
}
```

Then we expect such code is generated with KotlinPoet:

```kotlin
fun hogeWithKapt(arg: String) {
  // arg type is expected to be kotlin.String
}
```

But now we've got the code like:

```kotlin
fun hogeWithKapt(arg: java.lang.String) {
  // IDE flags warning about argument to use kotlin.String
}
```

Sorry I forgot to mention but our workaround is just for our library, so we don't have to consider any side effect about it(I didn't intend to add it to KotlinPoet for sure).

Anyway I realized it's kind of counter-intuitive because it means KotlinPoet user always take care about replacing java String to kotlin String. I don't come up with good way to deal with but I just reported as feedback 🙇

Please close this issue if it's not fit for your plan.

**Comment by JakeWharton** [comment] 2017-09-19 21:31
We might be able to pull the Kotlin type information from the metadata annotations automatically.

**Comment by swankjesse** [comment] 2017-09-19 21:54
Note that the two types aren’t interchangeable.

This compiles:
```
    val a : java.lang.String = java.lang.String("a")
    a.getBytes("UTF-8")
```

This doesn’t.
```
    val b : kotlin.String = "b"
    b.getBytes("UTF-8")
```

**Comment by tschuchortdev** [comment] 2018-03-02 12:53
The same thing happens with `kotlin.collections.List` which turns into `java.util.List` thus breaking the generated code. Is there a solution for this yet?

@JakeWharton getting the type information from metadata is indeed possible. [See](https://github.com/Takhion/kotlin-metadata/blob/master/lib/src/main/kotlin/me/eugeniomarletti/kotlin/metadata/KotlinMetadataUtils.kt#L130) which correctly returns ````` `kotlin`.`collections`.`List`<`S`>````` for the parameter I tested.

**Comment by richardwrq** [comment] 2018-03-22 09:17
I also have this problem, here is my solution.
I have defined an extension method for Element
`
private fun Element.javaToKotlinType(): ClassName? {
        val className = JavaToKotlinClassMap.INSTANCE.mapJavaToKotlin(FqName(this.asType().asTypeName().toString()))?.asSingleFqName()?.asString()
        return if (className == null) {
            null
        } else {
            ClassName.bestGuess(className)
        }
    }
`
you need to import kotlin-reflect

**Comment by tschuchortdev** [comment] 2018-03-23 21:56
@richardwrq it doesn't seem to be working for me with generic classes like `List`. The type is correctly resolved, but instead of importing `kotlin.collections.List` it imports `kotlin.collections.List<S>` which of course doesn't work. I'm tempted to just remove all `<.*?>` from imports in the resulting file, but that's somewhat of a hack.
What types did you test this with?

**Comment by RiccardoM** [comment] 2018-03-27 12:36
@JakeWharton Any news on this one?

**Comment by jdemeulenaere** [comment] 2018-03-31 20:51
I'm interested in this as well :)

**Comment by zigzago** [comment] 2018-04-01 12:39
@richardwrq @tschuchortdev This code is ok also for generic classes like List:

``` kotlin
fun Element.javaToKotlinType(): TypeName =
        asType().asTypeName().javaToKotlinType()

 fun TypeName.javaToKotlinType(): TypeName {
        return if (this is ParameterizedTypeName) {
            ParameterizedTypeName.get(
                rawType.javaToKotlinType() as ClassName,
                *typeArguments.map { it.javaToKotlinType() }.toTypedArray()
            )
        } else {
            val className =
                JavaToKotlinClassMap.INSTANCE.mapJavaToKotlin(FqName(toString()))
                    ?.asSingleFqName()?.asString()

            return if (className == null) {
                this
            } else {
                ClassName.bestGuess(className)
            }
        }
    }
``

**Comment by RiccardoM** [comment] 2018-04-03 06:25
@zigzago Works like a charm! Thank you

**Comment by StefMa** [comment] 2018-04-04 13:28
@zigzago 
This solution don't work with multiple generics:
`List<List<Boolean>>`
Will result in:
`<List<out java.util.List<out Boolean>>>`
(First `List` and last `Boolean` is correct. But second List is not correct).

I debugged a little bit and seems that the second `List` is not of type `ParameterizedTypeName`.

Additionally the solution uses `internal` APIs
```
import kotlin.reflect.jvm.internal.impl.name.FqName
import kotlin.reflect.jvm.internal.impl.platform.JavaToKotlinClassMap
```
which I don't want to rely on...

**Comment by zigzago** [comment] 2018-04-04 18:58
@StefMa this is strange, because `List<List<Boolean>>` is ok on my side (tested with annotated kotlin class, not java class).

Anyway my solution is a workaround. As mentioned above, kotlin metadata should be used to really fix the issue.

**Comment by burningfireplace** [comment] 2018-04-04 21:11
@zigzago 
you can combine your workaround with the extension from https://github.com/square/kotlinpoet/issues/330 to make the type nullable if necessary. But there are still issues with this workaround:
- nullable type parameters become non-nullable
- you can't use mutable collections (MutableList for example)

Anyway thanks for this solution!

@StefMa 
`List<List<Boolean>>` works fine for me. I tried it with the return type of a method (getter method for a field / kotlin property)

**Comment by epool** [comment] 2018-08-17 15:29
after 1.0.0-RC1 the [above answer](https://github.com/square/kotlinpoet/issues/236#issuecomment-377784099) will need some changes in order to work, these lines to be specific.

```
ParameterizedTypeName.get(rawType.javaToKotlinType() as ClassName, *typeArguments.map { it.javaToKotlinType() }.toTypedArray())
```
====>
```
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
...
(rawType.javaToKotlinType() as ClassName).parameterizedBy(*typeArguments.map { it.javaToKotlinType() }.toTypedArray())
```

**Comment by juanchosaravia** [comment] 2018-10-27 20:55
In version `1.3.0-rc-190` JavaToKotlinClassMap is not located anymore in the same package. 
Moved from
`import kotlin.reflect.jvm.internal.impl.platform.JavaToKotlinClassMap`
to
`import kotlin.reflect.jvm.internal.impl.builtins.jvm.JavaToKotlinClassMap`

**Comment by Erdenian** [comment] 2018-11-12 17:19
Api has changed little bit (use parameterizedBy instead of ParameterizedTypeName.get):
```
private fun TypeName.javaToKotlinType(): TypeName = if (this is ParameterizedTypeName) {
    (rawType.javaToKotlinType() as ClassName).parameterizedBy(
        *typeArguments.map { it.javaToKotlinType() }.toTypedArray()
    )
} else {
    val className = JavaToKotlinClassMap
        .INSTANCE
        .mapJavaToKotlin(FqName(toString()))?.asSingleFqName()?.asString()
    if (className == null) this
    else ClassName.bestGuess(className)
}
```

**Comment by TAGC** [comment] 2018-11-27 15:04
For me it's just `JavaToKotlinClassMap.mapJavaToKotlin` instead of `JavaToKotlinClassMap.INSTANCE.mapJavaToKotlin`

**Comment by dimsuz** [comment] 2019-03-04 10:38
I'd like to note that in light of this "bug", `FunSpec.overriding()` is nearly impossible to use in my project.
Once the method being overrided contains `String` or `List` or any other type with kotlin substitute, the generated code fails to compile.

God bless the opensource nature of this library and kotlin's functions extensions: I was able to copy paste `overriding()` implementation in my project as a `FunSpec` extension making it apply the above workarounds inside. But I would really like if this was somehow resolved by this library (although I understand why it's not).

**Comment by iamareebjamal** [comment] 2019-08-13 20:01
When we hoped this could get more attention, it gets moved to Icebox :(

**Comment by tschuchortdev** [comment] 2019-08-13 20:08
Hopefully this will be resolved in a future version with kotlinpoet-km which uses kotlinx-metadata. The metadata contains the _actual_ type names so it would even know if you are using java.lang types in your Kotlin code instead of indiscriminately mapping them to their Kotlin-equivalent in every case, like it was suggested in this issue. I'm also working on a library that will solve this but unfortunately it is far from finished.

**Comment by ZacSweers** [comment] 2019-08-14 01:51
The km artifact will help, but note that right now it only speaks classes. For cases like the overriding methods, we can maybe look at digging out the relevant metadata from the enclosing class. For cases like the TyperMirror.asTypeName() though there's really no way to know, as it depends on the context where it's defined. It would be better to get the metadata representation of the property/typevar/function/param/etc where it's defined

**Comment by ZacSweers** [comment] 2019-08-15 05:33
Quick prototype of a new `overriding` with the km APIs. It's heavyweight right now because we don't expose internal APIs to just read parts of a typespec, so it reads and renders the whole spec right now. If we add an API to control exactly what's parsed out of metadata we can reduce this cost.

```kotlin
fun FunSpec.Companion.overriding(element: ExecutableElement, types: Types): FunSpec.Builder {
    val enclosingClass = generateSequence<Element>(element) {
      it.enclosingElement
    }.first { it is TypeElement } as TypeElement

    val classMetadata = enclosingClass.toTypeSpec(elementHandlerFactoryCreator(this@KmSpecsTest)())
    val jvmSignature = element.jvmMethodSignature(types)
    val funSpec = classMetadata.funSpecs.find { it.tag<ImmutableKmFunction>()?.signature?.asString() == jvmSignature }
        ?: error("No matching funSpec found for $jvmSignature.")

    return funSpec.toBuilder()
        .clearBody() // Not in master, proposed in PR
  }

  @Test
  fun newOverriding() {
    val typeElement = elements.getTypeElement(Overriding::class.java.canonicalName)
    val testFunEE = ElementFilter.methodsIn(typeElement.enclosedElements)
        .find { it.simpleName.toString() == "testFunc" }!!

    //language=kotlin
    assertThat(FunSpec.overriding(testFunEE, types).build().toString().trim()).isEqualTo("""
      fun testFunc(input: kotlin.collections.MutableList<kotlin.Int?>): kotlin.String {
      }
    """.trimIndent())
  }

  class Overriding {
    fun testFunc(input: MutableList<Int?>): String {
      return ""
    }
  }
```

**Comment by AhmedMouradDev** [comment] 2019-10-19 22:34
Is the JavaToKotlinClassMap class still accessible? i can't seem to find it.

**Comment by JakeWharton** [comment] 2019-10-19 23:29
A map is not the correct nor accurate solution to this problem since it's not a 1:1 mapping. Multiple distinct Kotlin types are represented as the same JVM type and it's only exacerbated by inline classes. Parsing the metadata is the only way forward.

**Comment by AhmedMouradDev** [comment] 2019-10-20 15:28
I see, any plans to implement this in the near future or is it staying in the IceBox?

**Comment by tschuchortdev** [comment] 2019-10-20 17:04
Hasn't the metadata stuff already been merged?

**Comment by AhmedMouradDev** [comment] 2019-10-20 19:03
I'm using v1.4.1 and i still have this problem happening, so unless if i'm missing something, i don't think so.

**Comment by ZacSweers** [comment] 2019-10-20 20:02
The metadata artifacts are separate and were released in 1.4.0.

It’s important to understand that metadata annotations are only present on classes. Not individual functions, types, properties, parameters, or anywhere else. 

In short: cases like `TypeMirror.asTypeName()` or `Type.asTypeName()` will never work as intended for Kotlin compiler intrinsic types.  This means that APIs simply cannot look at individual types in isolation and have enough context to understand them. You _must_ have access to the appropriate metadata that describes them in context. There are no silver bullets here, this is how Kotlin works.

You can, however, derive the metadata context from navigable elements like methods, fields, etc. you simple traverse up it’s hierarchy to the first enclosing class, which will have the needed metadata annotation on it. Then you can connect that parsed information back to your source element and connect the dots to deduce the correct type. This is exactly how the snippet I provided above for `overriding` works, and it works with the 1.4.0 metadata release.

There is possibly an argument to be made that either kotlinpoet-metadata artifacts should live directly in the main KotlinPoet artifact, or the existing problematic APIs should be deprecated and moved into the kotlinpoet-metadata artifact where they can ask for the needed classpath information. At this point I think that’s a separate issue.

**Comment by ywwynm** [comment] 2019-11-20 09:43
@StefMa @zigzago `List<List<String>>` is converted to `kotlin.collections.List<out java.util.List<java.lang.String>>` for me, which isn't correct either. And I find the reason. That is, the first `List` is `ParameterizedTypeName` so that it can be handled properly. But the second `List` is actually `WildcardTypeName` (note the **out**).

Interestingly, if we have a `Map<List<Int>, List<Int>>`, it will be converted to `kotlin.collections.Map<kotlin.collections.List<kotlin.Int>, out java.util.List<java.lang.Integer>>>`, which means the first `List` is regarded as `ParameterizedTypeName` correctly, but at the same time the second is `WildcardTypeName`.

As a result, we can improve `javaToKotlinType` for `WildcardTypeName` case like this:

```
  fun TypeName.javaToKotlinType(): TypeName {
    return when (this) {
      is ParameterizedTypeName -> {
        (rawType.javaToKotlinType() as ClassName).parameterizedBy(*(typeArguments.map { it.javaToKotlinType() }.toTypedArray()))
      }
      is WildcardTypeName -> {
        outTypes[0].javaToKotlinType()
      }
      else -> {
        val className = JavaToKotlinClassMap.INSTANCE.mapJavaToKotlin(FqName(toString()))?.asSingleFqName()?.asString()
        return if (className == null) {
          this
        } else {
          ClassName.bestGuess(className)
        }
      }
    }
  }
```

And now it should work while I didn't test it thoroughly.

**Comment by KirillVolkov** [comment] 2019-11-27 15:22
`
private fun TypeName.javaToKotlinType(): TypeName {

        return when (this) {
            is ParameterizedTypeName -> {
                (rawType.javaToKotlinType() as ClassName).parameterizedBy(
                    *typeArguments.map {
                        it.javaToKotlinType()
                    }.toTypedArray()
                )
            }
            is WildcardTypeName -> {
                val type =
                    if (inTypes.isNotEmpty()) WildcardTypeName.consumerOf(inTypes[0].javaToKotlinType())
                    else WildcardTypeName.producerOf(outTypes[0].javaToKotlinType())

                diagnostic(type.toString())
                type
            }

            else -> {
                val className = JavaToKotlinClassMap
                    .mapJavaToKotlin(FqName(toString()))?.asSingleFqName()?.asString()
                if (className == null) {
                    this
                } else {
                    ClassName.bestGuess(className)
                }
            }
        }
    }
`

**Comment by JohnOberhauser** [comment] 2020-02-07 01:22
Is there a "correct" way to handle this yet?

**Comment by ZacSweers** [comment] 2020-02-07 01:23
Yes, use the metadata APIs.

**Comment by JohnOberhauser** [comment] 2020-02-07 01:24
@ZacSweers are there any examples on how to use that?

**Comment by ZacSweers** [comment] 2020-02-07 01:29
Did you look at the readmes on both metadata artifacts?

**Comment by andromedcodes** [comment] 2020-04-20 19:30
Is there any resource/example one could follow to use the metadata APIs? I can't rely on the documentation of the metadata artefact as it's not clear at all.

**Comment by ZacSweers** [comment] 2020-04-20 19:43
@andromedcodes there are READMEs in their modules. If those aren't sufficient, PR suggested improvements.

**Comment by andromedcodes** [comment] 2020-04-20 19:46
@ZacSweers do you mean this?  https://github.com/square/kotlinpoet/tree/master/kotlinpoet-metadata

**Comment by ZacSweers** [comment] 2020-04-20 19:47
https://github.com/square/kotlinpoet/blob/master/kotlinpoet-metadata/README.md

**Comment by andromedcodes** [comment] 2020-04-20 19:52
Thanks. I have a question if I may. I have this annotation 
```
@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.CLASS)
annotation class Destination(
        val name: String = "",
        val args: Array<Arg> = []
)

@Retention(AnnotationRetention.SOURCE)
@Target(AnnotationTarget.VALUE_PARAMETER)
annotation class Arg(
        val name: String,
        val type: KClass<*>,
        val nullable: Boolean = false
)
```
as you can see args is an annotation but is used as an array of values in `Destination`
In the `Arg` annotation I pass a `KClass<*>`  so i can generate later using kotlinpoet the parameter needed for this class. I have the same problem as above and I am stuck with the Type mirror giving me the java.lang.String instead of kotlin String class.
Any ideas how to solve this? or at least if you can point me to the right direction if I am doing something wrong. 
PS: I can post the code if you need more in-depth look
Many thanks

**Comment by ZacSweers** [comment] 2020-04-20 19:55
Please ask usages questions on stackoverflow. Given the general availability of metadata support, in going to close this issue out.

**Closed by ZacSweers** 2020-04-20 19:55 UTC

**Comment by andromedcodes** [comment] 2020-04-20 20:58
For any future reader here is a very interesting talk about metadata @JohnOberhauser 
https://www.youtube.com/watch?v=uHPti6Z02tI

**Comment by obenabde** [comment] 2020-05-27 22:22
Hey @ZacSweers I'm trying to use the overriding implementation provided above, but the "jvmMethodSignature" method in:

val jvmSignature = element.jvmMethodSignature(types)

can't be found anywhere. Has this been deleted? If or otherwise, is it possible to get an updated version of the code above? (also the test in the snippet uses the old signature, it needs newly added third parameter.)

**Comment by bhargavms** [comment] 2020-09-05 15:39
Are there any documentation for kotlinpet metadata anywhere?

**Comment by ZacSweers** [comment] 2020-09-05 17:47
> Are there any documentation for kotlinpet metadata anywhere?

Did you look at their READMEs?

**Comment by ZacSweers** [comment] 2020-09-05 17:48
> Are there any documentation for kotlinpet metadata anywhere?

Did you look at their docs on the project site? 

https://square.github.io/kotlinpoet/kotlinpoet_metadata/

https://square.github.io/kotlinpoet/kotlinpoet_metadata_specs/

**Comment by CasualGitEnjoyer** [comment] 2022-09-27 20:42
> > Are there any documentation for kotlinpet metadata anywhere?
> 
> Did you look at their docs on the project site?
> 
> https://square.github.io/kotlinpoet/kotlinpoet_metadata/
> 
> https://square.github.io/kotlinpoet/kotlinpoet_metadata_specs/

FYI both doc links are broken

**Comment by richardwrq** [comment] 2022-09-27 20:43
您的来信已收到。谢谢

**Comment by Egorand** [comment] 2022-09-28 09:53
@CasualGitEnjoyer the artifacts have been renamed, which invalidated the old URLs. Here's an up-to-date link for interop-kotlinx-metadata docs: https://square.github.io/kotlinpoet/interop-kotlinx-metadata/.
