### ISSUE TITLE
NameAllocator.newName appends an underscore to data when it is legal

### ISSUE THREAD

**Issue by eygraber** [square/kotlinpoet#1042] opened 2021-03-03 06:13 UTC
The following code will output:

```
public class Test(
  public val data_: kotlin.String
)
```

Even though:

```
public class Test(
  public val data: kotlin.String
)
```

is valid Kotlin.

```
val propertyName = NameAllocator().newName("data")

val typeSpec = TypeSpec
    .classBuilder("Test")
    .primaryConstructor(
        FunSpec
            .constructorBuilder()
            .addParameter(
                ParameterSpec
                    .builder(propertyName, String::class)
                    .build()
            )
            .build()
    )
    .addProperty(
        PropertySpec
            .builder(propertyName, String::class)
            .initializer(propertyName)
            .build()
    )
    .build()
```

**Comment by ZacSweers** [comment] 2021-03-03 06:14
This is intentional, namallocator always avoids collisions with kotlin keywords

**Comment by Egorand** [comment] 2021-03-03 14:47
Yep, we're escaping keywords more aggressively since 1.7.0. I'll close this issue for now since it's not a bug, but happy to reopen if there's additional info.

**Closed by Egorand** 2021-03-03 14:47 UTC
