### ISSUE TITLE
FunSpec.overriding does not handle internal methods correctly

### ISSUE THREAD

**Issue by Leland-Takamine** [square/kotlinpoet#828] opened 2019-11-05 02:34 UTC
### Repro Steps

```bash
git clone git@github.com:Leland-Takamine/kotlinpoet-repro.git
cd kotlinpoet-repro
./gradlew :build
# Build fails
```

##### Method to be overridden

```kotlin
class Foo {
    internal abstract fun myMethod()
}
```

##### Overriding method generated via `FunSpec.overriding(...)`

```kotlin
class FooImpl : Foo() {
  override fun myMethod$repro(): Unit = throw UnsupportedOperationException()
}
```

Notice that the generated method includes the `$repro` suffix. This is due to the fact that Kotlin [mangles the names of internal methods](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#visibility).

### Possible Solution

KotlinPoet should inspect the Kotlin metadata to use the original method name for overriding.

**Comment by Leland-Takamine** [comment] 2019-11-05 02:35
@tyvsmith @kurtisnelson

**Comment by ZacSweers** [comment] 2019-11-05 06:00
Heavily discussed in #236

**Comment by Egorand** [comment] 2019-11-07 12:58
@Leland-Takamine KotlinPoet does work with Kotlin metadata but through different API, please refer to https://github.com/square/kotlinpoet/blob/master/kotlinpoet-metadata-specs/README.md and https://github.com/square/kotlinpoet/blob/master/kotlinpoet-metadata/README.md.

We should probably deprecate existing introspection API since they don't work well with Kotlin.

**Comment by ZacSweers** [comment] 2019-11-09 23:14
+1 on deprecating the existing. It's a straight port from javapoet but is wrong often enough to be untrustworthy

**Comment by ZacSweers** [comment] 2019-12-26 07:15
Folding this into #236 since it's basically a duplicate of the discussion there.

**Closed by ZacSweers** 2019-12-26 07:15 UTC
