### ISSUE TITLE
Cannot use static methods from kotlin code

### ISSUE THREAD

**Issue by fab1an** [square/kotlinpoet#167] opened 2017-06-30 14:01 UTC
Methods such as `fun TypeElement.asClassName(): ClassName` aren't accessible from kotlin-code for some reason.

**Comment by JakeWharton** [comment] 2017-06-30 14:08
Dupe of #141. This is an IntelliJ bug, although I'm planning on moving these methods anyway.

**Closed by JakeWharton** 2017-06-30 14:08 UTC
